/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.1
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2017 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "MIDI_UART.h"
#include "USBMIDI.h"
#include "USBMIDI_audio.h"
#include "USBMIDI_cdc.h"
#include "USBMIDI_hid.h"
#include "USBMIDI_midi.h"
#include "USBMIDI_pvt.h"
#include "USBMIDI_cydmac.h"
#include "USBMIDI_msc.h"
#include "UART.h"
#include "UART_PVT.h"
#include "I2C.h"
#include "I2C_PVT.h"
#include "SCL_aliases.h"
#include "SCL.h"
#include "SDA_aliases.h"
#include "SDA.h"
#include "MIDI_UART_IntClock.h"
#include "USBMIDI_Dm_aliases.h"
#include "USBMIDI_Dm.h"
#include "USBMIDI_Dp_aliases.h"
#include "USBMIDI_Dp.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"

/*[]*/

